name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          check-latest: true
      - name: Build (Not Windows)
        if: matrix.os != 'windows-latest'
        run: 'go build -v -o generate-ddg_${{ matrix.os }}'
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: 'go build -v -o generate-ddg_${{ matrix.os }}.exe'
      - uses: actions/upload-artifact@v4
        with:
          name: generate-ddg_${{ matrix.os }}
          path: 'generate-ddg_${{ matrix.os }}*'